// <auto-generated />
using Anon.NET.Sample.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Anon.NET.Sample.Api.Migrations
{
    [DbContext(typeof(SampleDbContext))]
    [Migration("20250528135152_InicializacaoBanco")]
    partial class InicializacaoBanco
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Anon.NET.Sample.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CEP")
                        .HasColumnType("longtext");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Salario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CEP = "01310-100",
                            CPF = "790.840.080-90",
                            Email = "joao@example.com",
                            Idade = 28,
                            Name = "João Silva",
                            Salario = 4500
                        },
                        new
                        {
                            Id = 2,
                            CEP = "04567-020",
                            CPF = "286.993.070-47",
                            Email = "maria@example.com",
                            Idade = 35,
                            Name = "Maria Santos",
                            Salario = 6200
                        },
                        new
                        {
                            Id = 3,
                            CEP = "22070-030",
                            CPF = "583.760.150-36",
                            Email = "pedro@example.com",
                            Idade = 42,
                            Name = "Pedro Oliveira",
                            Salario = 7800
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
